### PR TITLE
enable library evolution

### PR DESCRIPTION
**Pull request by danil-z**
add library evolution support, for more info please visit https://www.swift.org/blog/library-evolution/

### CODE REVIEW

**Comment by hmlongco** [comment]
I'll need to look at the pros and cons of doing this...

**Comment by waltarmour** [comment]
I can say that we would appreciate having this enabled.  Using Factory in another library/SDK gets more complicated without it.

**Comment by doozMen** [comment]
Occording to the documentation this is not needed for spm libraries that are distributed via spm and build with the client [Library evolution support should only be used when a framework is going to be built and updated separately from its clients](https://www.swift.org/blog/library-evolution/#:~:text=Library%20evolution%20support%20should%20only%20be%20used%20when%20a%20framework%20is%20going%20to%20be%20built%20and%20updated%20separately%20from%20its%20clients.)

So this should not be added as it might confuse people.

**Comment by hmlongco** [comment]
I'm closing this one. If it still warrants discussion create a thread in Discussions for it. For consideration I need to know what benefits it provides as well as what impact, if any, it would have on existing code and projects.

**Pull request closed without merging**
